FROM node:24-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY ../frontend-service .

RUN npm run build

# Установка serve для раздачи статики
RUN npm install -g serve

EXPOSE 8080

CMD ["serve", "-s", "dist", "-l", "8080"]